### ISSUE TITLE
Bulk Model Deletion

### ISSUE THREAD

**Issue by nickrsan** [Water-Systems-Management-UCM/Waterspout#17]
We can currently delete a single model run, but there's no way to delete many of them at a time from the model run list

- [x] Also need a way to confirm deletion after they click - modal or in-place change to the button - both for the single item removal and the bulk item removal

**Comment by nickrsan** [comment]
Hey Lorenzo - I'm adding you to this task - We have a way to delete model runs from the individual model run pages, but I'd like to make it work for many model runs by checking the box on the model run list page - I'd say this can be a lower priority task for you, but it could be a decent one to get started with because there's already code/a button to handle deletion in the ModelRun.vue component (that calls some global Vuex methods to handle the bulk of the work - the ModelRun.vue code is mostly to handle the button/confirmation). We can discuss more when you're ready to start in on this task

**Comment by gr8monk3ys** [comment]
Extra items: Delete shows up only when items are selected
Button makes a change to confirm instead of modal
in the end, there is an update
