### ISSUE TITLE
Minimum restrictions by crop 

### ISSUE THREAD

**Issue by josemrodriguezf** [Water-Systems-Management-UCM/Waterspout#24]
I don't remember if DAP has this restrictions, we created a dynamic directory depending on what crops are produced in each region and then it adds a crop specific restriction. In Kern we have this

**Comment by nickrsan** [comment]
Thanks Jose - can you clarify what you mean by minimum restrictions? Are you saying the land area used for a given crop? That's on the timeline (a min and max value both), but not sure it'll make it in time for the November deliverable unless you, @alesbou and @scoleUCM think it is a priority feature to add.

**Comment by josemrodriguezf** [comment]
Yes, for a specific scenario define a minimum constraint for specific crops based on the observed land. I would say it is a priority, it seems in the Delta they care about keeping specific amount of cropland for corn.

**Comment by nickrsan** [comment]
OK, great - this has been implemented and included. Thanks!
