### ISSUE TITLE
Region Modeling Type not correctly highlighting the selected option

### ISSUE THREAD

**Issue by Shivneel7** [Water-Systems-Management-UCM/Waterspout#67]
When using advanced option on crop cards, user is able to unselect both options.
![image](https://user-images.githubusercontent.com/18388474/119903976-6c20ed80-befe-11eb-86ba-d1e5d1a4400b.png)

**Comment by nickrsan** [comment]
From Shivneel:

[3:03 PM] Shivneel Chand
    So when you click "advanced" on a card, it shows up as "modeled" being auto selected
​[3:04 PM] Shivneel Chand
    If I click the option that is already selected, then you can make it so neither is selected
​[3:05 PM] Shivneel Chand
    you can see that the bottom one is the default setting, and the top one has nothing selected
​[3:08 PM] Shivneel Chand
    I just created a model run, and whichever one was clicked last is the one that gets used when creating the model

**Comment by nickrsan** [comment]
OK, I think this is a simple fix - I just needed to add "mandatory" as a property to the button-toggle group: https://vuetifyjs.com/en/components/button-groups/#api

I've added it, but haven't tested it yet - going to leave this open until I return to coding/testing

**Comment by nickrsan** [comment]
OK, yes, this issue has been resolved
