### ISSUE TITLE
Adding then removing upper limit on crop cards causes table to have blank values for 'Max Land Area%'

### ISSUE THREAD

**Issue by Shivneel7** [Water-Systems-Management-UCM/Waterspout#69]
![image](https://user-images.githubusercontent.com/18388474/121592462-8fb06180-c9ef-11eb-9f4a-75848efcbb58.png)

Adding then removing upper limit on crop cards causes table to have blank values for 'Max Land Area%' rather than saying "No Limit" as it should.

**Comment by nickrsan** [comment]
This was addressed in Water-Systems-Management-UCM/stormchaser@546d1d3a98dc48f47bcaa65c785b577e96c1304c
